/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as UserImport } from './routes/_user'
import { Route as IndexImport } from './routes/index'
import { Route as UserIndexImport } from './routes/_user/index'
import { Route as UserSettingsImport } from './routes/_user/settings'
import { Route as UserItemsImport } from './routes/_user/items'
import { Route as UserAdminImport } from './routes/_user/admin'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const UserRoute = UserImport.update({
  id: '/_user',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserIndexRoute = UserIndexImport.update({
  path: '/',
  getParentRoute: () => UserRoute,
} as any)

const UserSettingsRoute = UserSettingsImport.update({
  path: '/settings',
  getParentRoute: () => UserRoute,
} as any)

const UserItemsRoute = UserItemsImport.update({
  path: '/items',
  getParentRoute: () => UserRoute,
} as any)

const UserAdminRoute = UserAdminImport.update({
  path: '/admin',
  getParentRoute: () => UserRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_user': {
      preLoaderRoute: typeof UserImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_user/admin': {
      preLoaderRoute: typeof UserAdminImport
      parentRoute: typeof UserImport
    }
    '/_user/items': {
      preLoaderRoute: typeof UserItemsImport
      parentRoute: typeof UserImport
    }
    '/_user/settings': {
      preLoaderRoute: typeof UserSettingsImport
      parentRoute: typeof UserImport
    }
    '/_user/': {
      preLoaderRoute: typeof UserIndexImport
      parentRoute: typeof UserImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  UserRoute.addChildren([
    UserAdminRoute,
    UserItemsRoute,
    UserSettingsRoute,
    UserIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
